# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      local-dir: docs
      fqdn: lobstr.r-lib.org
      on:
        branch: master

r:
- 3.1
- 3.2
- 3.3
- oldrel
- devel

after_success:
  - Rscript -e 'covr::codecov()'
